CONF_CLOSE_SECONDS = "close_seconds"
CONF_OPEN_SECONDS = "open_seconds"
CONF_SYNC_SECONDS = "sync_seconds"

CONF_SUPPORTS_MID = "midpoint_supported"
CONF_STEPS_MID = "midpoint_steps"
CONF_SYNC_MID = "midpoint_sync"

CONF_TILT_POS1_MS = "tilt1_ms"
CONF_TILT_POS2_MS = "tilt2_ms"

DEF_CLOSE_SECONDS = 30
DEF_OPEN_SECONDS = 30
DEF_SYNC_SECONDS = 2
DEF_SUPPORTS_MID = False
DEF_STEPS_MID = 10
DEF_SYNC_MID = False

DEF_TILT_POS1_MS = 1750
DEF_TILT_POS2_MS = 1750

DEVICE_PACKET_TYPE_BLINDS1 = 0x19
DEVICE_PACKET_SUBTYPE_BLINDST19 = 0x13
DEVICE_PACKET_TYPE_RFY = 0x1a

DEVICE_TYPE_VOGUE_VERTICAL = "VogueVert"
